branch-defaults:
  development:
    environment: geo-arg-server-dev
    group_suffix: null
global:
  application_name: geo-arg-server
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-southeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
